// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmlpcztlkvfweqvhjjfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtbHBjenRsa3Zmd2VxdmhqamZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODUwNzksImV4cCI6MjA2NTY2MTA3OX0.HxUU30iyX7DVNc_QWzs64L34suO13BxKhdE0yA1cBWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);